/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Clases.Grafo;
import Clases.Pintar;
import java.awt.Frame;
import javax.swing.JOptionPane;


public class EliminarAristas extends javax.swing.JFrame {
int i;
 
public void repaintA(){
        for (int j = 0; j < i; j++) {
            for (int k = 0; k < i; k++) {
                if(grafo.getmAdyacencia(j, k) == 1)
                Pintar.pintarLinea(Main.panelGrafo.getGraphics(),grafo.getCordeX(j),grafo.getCordeY(j), grafo.getCordeX(k), grafo.getCordeY(k),grafo.getmCoeficiente(j, k));
            }
        }
        for (int j = 0; j < i; j++) {
            Pintar.pintarCirculo(Main.panelGrafo.getGraphics(), grafo.getCordeX(j),grafo.getCordeY(j),String.valueOf(grafo.getNombre(j)), grafo.getNombre2(i));
           
       }
   }
 Pintar pintar ;
      Grafo grafo ;
      Frame frame;
    public EliminarAristas(Pintar  pintar , Grafo grafo ,int ii, Frame frame) {
        initComponents();
        i=ii;
        this.pintar = pintar;
       this.grafo=grafo;
       this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEA = new javax.swing.JPanel();
        text2 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Eliminar Arista");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        panelEA.setLayout(null);

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        text2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text2KeyReleased(evt);
            }
        });
        panelEA.add(text2);
        text2.setBounds(250, 30, 40, 22);

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text1KeyReleased(evt);
            }
        });
        panelEA.add(text1);
        text1.setBounds(180, 30, 40, 22);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelEA.add(jButton1);
        jButton1.setBounds(10, 30, 90, 22);

        jLabel2.setText("arista entre");
        panelEA.add(jLabel2);
        jLabel2.setBounds(110, 30, 100, 16);

        jLabel1.setText("y");
        panelEA.add(jLabel1);
        jLabel1.setBounds(230, 30, 110, 16);

        getContentPane().add(panelEA);
        panelEA.setBounds(10, 0, 330, 90);

        setBounds(60, 130, 374, 138);
    }// </editor-fold>//GEN-END:initComponents

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void text2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2KeyPressed

    private void text2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text2KeyReleased
        String tem = new String(text2.getText());
        StringBuffer tem2= new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if(Character.isDigit(tem.charAt(j))){
                tem2.append(tem.charAt(j));
            }
        }
        text2.setText(""+tem2);
    }//GEN-LAST:event_text2KeyReleased

    private void text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text1KeyReleased
        String tem = new String(text1.getText());
        StringBuffer tem2= new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if(Character.isDigit(tem.charAt(j))){
                tem2.append(tem.charAt(j));
            }
        }
        text1.setText(""+tem2);        // TODO add your handling code here:
    }//GEN-LAST:event_text1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x;int y;
        if(text2.getText().length()<1 || text1.getText().length()<1 )
        JOptionPane.showMessageDialog(null,"Digite los datos");
        else{
            x=Integer.parseInt(text2.getText());
            y=Integer.parseInt(text1.getText());
           
            if(x<0 || x>=i || y<0 || y>=i || x==y){
                JOptionPane.showMessageDialog(null,"Digite los nodos correctos");
            }else{
                grafo.setmAdyacencia(x, y, 0);
                grafo.setmAdyacencia(y, x, 0);
                grafo.setmCoeficiente(x, y, 0);
                grafo.setmCoeficiente(y, x, 0);
                text2.setText(null);
                text1.setText(null);
                Main.panelGrafo.paint(Main.panelGrafo.getGraphics());
                
               repaintA();

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      frame.setEnabled(true);  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarAristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelEA;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
