/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Clases.Grafo;
import java.awt.Frame;
import Clases.DJ;
import Clases.Floyd;

public class Matrices extends javax.swing.JFrame {

    /**
     * Creates new form Matrices
     */
    Grafo grafo;
    Frame frame;
    public Matrices(int tope,Grafo arboles,Frame frame ) {
        this.i=tope;
        this.grafo=arboles;
        this.frame = frame;
        
        initComponents();
int[][] Recorrido = new int[tope][tope];

        Floyd floyd = new Floyd(grafo, tope, Recorrido);
        int[][] matrix;
        matrix = floyd.Floyd(tope);
        panelMatriz.append("Matriz de Costos\n");
        for (int j = 0; j < tope; j++) {
            panelMatriz.append(" " + grafo.getNombre(j) + "\t");
        }
        panelMatriz.append("\n");
        for (int j = 0; j < tope; j++) {

            for (int k = 0; k < tope; k++) {
                if (matrix[j][k] == 0) {
                    panelMatriz.append(" " + "∞" + "\t");
                } else {
                    panelMatriz.append(" " + matrix[j][k] + "\t");
                }

            }
            panelMatriz.append("\n");
        }
        panelMatriz.append("\n");
        panelMatriz.append("\n");
        panelMatriz.append("Matriz de Recorridos\n");
        for (int j = 0; j < tope; j++) {
            panelMatriz.append(" " + grafo.getNombre(j) + "\t");
        }
        panelMatriz.append("\n");
        for (int j = 0; j < tope; j++) {

            for (int k = 0; k < tope; k++) {
                if (matrix[j][k] == 0) {
                    panelMatriz.append(" " + "-" + "\t");
                } else {
                    panelMatriz.append(" " + Recorrido[j][k] + "\t");
                }

            }
            panelMatriz.append("\n");
        }    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelMatriz = new javax.swing.JTextArea();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        panelMatriz.setEditable(false);
        panelMatriz.setColumns(20);
        panelMatriz.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        panelMatriz.setRows(5);
        jScrollPane1.setViewportView(panelMatriz);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 560, 400);

        setSize(new java.awt.Dimension(635, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frame.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Matrices().setVisible(true);
            }
        });
    }
int i;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea panelMatriz;
    // End of variables declaration//GEN-END:variables
}
